kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  labels:
    tier: backend
  name: mongo-persistent-storage
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}
