apiVersion: v1
kind: Service
metadata:
  name: my-parse-app-service
spec:
  ports:
  - port: 1337
    targetPort: 1337 
    protocol: TCP
    name: my-parse-app-service
  type: LoadBalancer 
  selector:
    app: my-parse-app  
